import * as fs from 'fs';

// Path to the JSON report generated by Playwright
const reportPath = './results.json';

// Read the JSON report
const report = JSON.parse(fs.readFileSync(reportPath, 'utf-8'));

// Modify the 'reporter' field
report.config.reporter = {
  "html": null,
  "json": {
    "outputFile": "results.json"
  },
  "allure": {
    "detail": true,
    "outputFolder": "allure-results",
    "suiteTitle": false
  }
};

// Write the modified report back to the file
fs.writeFileSync(reportPath, JSON.stringify(report, null, 2));

console.log('Modified the Playwright JSON report successfully.');
